### ISSUE TITLE
The "PublicizeTask" task failed unexpectedly. The file already exists.

### ISSUE THREAD

**Issue by AlexejheroYTB** [BepInEx/BepInEx.AssemblyPublicizer#4]
>  BepInEx.AssemblyPublicizer.MSBuild.props(11, 9): [MSB4018] The "PublicizeTask" task failed unexpectedly.
System.IO.IOException: The file 'C:\Repos\Submerged\Client\Submerged\obj\Submerged\Debug\net6.0\publicized\Il2CppInterop.Runtime.xml' already exists.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at BepInEx.AssemblyPublicizer.MSBuild.PublicizeTask.Execute() in /home/runner/work/BepInEx.AssemblyPublicizer/BepInEx.AssemblyPublicizer/BepInEx.AssemblyPublicizer.MSBuild/PublicizeTask.cs:line 66
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

**Comment by js6pak** [comment]
7181be4080292ffecf97919f832cc6495e8a76f6
